# Rest in string_map.json
# We don't use them but I wanted to document them for debugging purposes.
# We use the below sometimes since they're error codes from the API.
error_code_map = {
    "param_error": "The requested data is invalid!",
    "no_permission": "No permission",
    "first_login": "Please set password",
    "passwd_weak_login": "Weak password",
    "time_abnormal_login": "System time is abnormal, please change the password",
    "passwd_expired_login": "Password has expired. Please set it again",
    "passwd_expires_state": "password expires state",
    "save_failed": "Save Failed!",
    "search_failed": "Search Failed!",
    "device_play_locked": "The device is in playback mode, please try again later!",
    "pwd_weak_rule": "The password does not meet the requirements.",
    "current_pwd_error": "Incorrect password",
    "current_pwd_error_ntime": "The password has been entered incorrectly 5 times. Please try again in % seconds.",
    "session_invalid": "Session invalid",
    "network_error": "Network error",
    "data_error": "data error",
    "filename_error": "filename error",
    "file_error": "Error file!",
    "upgrade_failed": "upgrade failed!",
    "username_error": "User name error",
    "overreach": "Unauthorized",
    "short_modify_time": "The password change interval is too short.",
    "unmatched_pwd": "The passwords you entered do not match. Please try again",
    "pwd_empty": "Password cannot be empty!",
    "pwd_length_err": "The password length is not in line with the rules",
    "pwd_equal_name": "The password cannot be the same as the username or the username written backwards",
    "pwd_equal_old": "The new password cannot be the same as the previous two passwords",
    "pwd_repeated": "The new password and the old password must have two different characters",
    "part_failed": "The following channel parameters failed to save",
    "user_auth_failed": "Invalid username or password!",
    "net_unreachable_or_dns_wrong": "Network cannot access or DNS is incorrect!",
    "check_smtp_port": "Connect Error! Please check the SMTP PORT!",
    "tls_ssl_handshake_err": "TLS/SSL link error!",
    "email_connect_err": "Connection error! Please check the recipient's email!",
    "not_modified": "No change!",
    "http_redirect_https": "HTTP turns HTTPS",
    "not_found": "not found",
    "method_not_allowed": "Request methods are not allowed!",
    "payload_too_large": "Data overload",
    "uri_too_long": "URI Too Long",
    "internal_server_error": "Internal server error",
    "install_failed": "Installation failed",
    "uninstall_failed": "Uninstall Failed",
    "uninstall_not_allow": "Uninstall is not allowed while in use",
    "switch_failed": "Certificate switch failed",
    "upload_failed": "Uninstall Failed",
    "upload_success": "Installation successful",
    "length_too_long": "The data is too big",
    "unsafe_siganature": "Unsafe certificate",
    "cert_key_not_match": "Certificate mismatch",
    "invalid_cert_time": "Invalid certificate time",
    "invalid_private_key": "Invalid private key file",
    "invalid_cert": "Invalid certificate file",
    "invalid_key_usage": "Invalid certificate key usage",
    "invalid_cert_chain": "Invalid certificate chain",
    "invalid_cacert": "Invalid root certificate",
    "invalid_cacert_time": "Contains an invalid root certificate",
    "token_generation_failed": "Token generation failed",
    "token_invalid": "Token invalid",
    "lack_memory": "Out of Memory",
    "no_need_upgrade": "Current version is up to date",
    "updating": "Upgrade in Progress",
    "in_user_interface": "Local User Operation in Progress, Cannot Start Upgrade!",
    "localuser_operating_cannot_talkback": "Local User Operation in Progress, Cannot Start Talkback!",
    "upgrade_memory_not_enough": "Out of Memory",
    "upgrade_file_error": "Error file!",
    "upgrade_parameter_error": "Error parameters",
    "upgrade_no_u_disc": "USB device not found",
    "upgrade_no_upgrade_software": "Current version is up to date",
    "upgrade_software_is_new": "Current version is up to date",
    "upgrade_software_packet_error": "Error file!",
    "upgrade_language_version_error": "Get device language error",
    "upgrade_file_name_too_long": "File name overlength",
    "upgrade_exit": "upgrade failed!",
    "upgrade_uncipher": "upgrade failed!",
    "upgrade_download_faild": "Download firmware failed",
    "upgrade_download_network_error": "Network not connected",
    "upgrade_environmentvar_different": "The software storage partition has been modified. Please use FAT32 USB flash disk to upgrade the device",
    "upgrade_usbtype_error": "upgrade failed!",
    "verify_failed": "Username or Password Error!",
    "login_block": "Account locked. Try again in -- seconds.",
    "login_failed_or_block": "Incorrect username or password, if you have tried many times, please try again after '-- minutes'",
    "login_failed_or_block_second": "Incorrect username or password, if you have tried many times, please try again after '-- seconds'",
    "black_ip": "The local IP address is forbidden.",
    "connect_server_err": "Connect Server Error!",
    "operation_failed": "Operation failure",
    "illegal_operation": "Please close __SMARTARR__",
    "no_login": "No login",
    "expired": "Login timeout. Log in again.",
    "one_IE": "Other users log in at this IP, the current user has been forced to go offline.",
    "logout": "Have to log out",
    "login_at_other": "The account is in use.",
    "device_reboot": "System restarting...",
    "passwd_expired": "Password expired, please login again to set!",
    "param_changed": "User parameters changed, please log in again!",
    "network_changed": "Network parameters changed, please log in again!",
    "ssl_error": "certificate expires.",
    "format_failed": "Formatting failed",
    "frequent_operation": "Operation Frequently",
    "check_ver_timeout": "Version detection timeout",
    "check_ver_error": "Unable To Find Latest Version",
    "get_packsize_failed": "Get upgrade package size failed",
    "upgrade_pack_toolarge": "Upgrade firmware oversize",
    "pack_download_fialed": "Upgrade pack download failed",
    "connect_error": "Network Connection Error!",
    "send_error": "Send Error",
    "reveive_error": "Receive error",
    "network_info_error": "Network information error",
    "connect_server_timeout": "Connect Server Timeout!",
    "user_authentication_failed": "User authentication failed",
    "send_request_timeout": "Send request to dyndns server timeout!",
    "ddns_server_response_timeout": "DDNS server response time out!",
    "host_name_abnormal": "Hostname exception",
    "domain_name_incomplete": "Incomplete domain name",
    "username_or_password_empty": "Invalid username or password!",
    "too_many_or_too_few_hosts_found": "Too many or too few hosts found!",
    "dns_service_error": "DDNS Service Error! Try 1 hour later!",
    "requested_ip_address_failed": "Request IP address Failed!",
    "unknown_error": "Unknown Error!",
    "cloud_video_upload_chn_limit": "The number of open channels for cloud video has reached the maximum. Please refresh the page or close the relevant buttons",
    "cloud_active_failed": "Get Authenticate Link Failure!",
    "handle_processed": "Error",
    "illegal_param": "Illegal parameter",
    "connect_failed": "Ftp connection failed",
    "login_failed": "Login failed",
    "write_file_failed": "Write failure",
    "created_dir_failed": "Creation failed",
    "system_error": "System error.",
    "connect_ip_server_timeout": "Connect IP Server Timeout!",
    "connect_ddns_server_timeout": "Connect DDNS Server Timeout!",
    "send_request_to_server_timeout": "Sending request to DDNS server timed out",
    "server_response_timeout": "Server response timed out!",
    "invalid_username_or_password": "Invalid username or password!",
    "hostname_not_exist": "Hostname does not exist!",
    "hostname_or_username_not_exist": "Hostname or username does not exist!",
    "hostname_blocked": "The host name exists but is locked!",
    "username_or_passwore_is_empty": "The username or password cannot be empty!",
    "not_donator_stop_update": "Not donator, update stopped !",
    "not_fully_qualified_domain_name": "Not a fully qualified Hostname!",
    "host_under_different_account": "The host exists but under a different account!",
    "modify_failed": "Modify Failed",
    "c23_pwd_check_failed": "1. 8~9 characters: combination should consist of at least 3 from uppercase letters, lowercase letters, numbers or special characters. 2. 10~15 characters: combination should consist of at least 2 from uppercase letters, lowercase letters, numbers or special characters. 3. Repeated and continuous characters exceed 4-digit are prohibited. i.e., 6666/bbbb or 1234/abcd. 4. Continuous keys of keyboard pattern exceed 4-digit are prohibited. i.e., qwer or ghjk",
    "data_saving_busy": "frequent operation, please try again later!",
    "network_port_conflict": "Port conflict, please replace the port!",
    "analog_chn_limit": "The number of analog channels supported by intelligent switch has reached the upper limit. Please refresh the page or close the relevant button",
    "file_invalid": "File error, please select a legal file!",
    "user_expired": "The main user information has been modified, please log in again",
    "ip_filter_list_empty": "Please add at least one enabled IP",
    "connet_close": "Device connection abnormal",
    "ver_err": "Upgrade file does not match",
    "not_exist": "Device is offline",
    "upgrading": "IPC equipment is being upgraded",
    "read_file_fail": "Error reading file",
    "upgradeFailed": "upgrade failed",
    "file_creation_error": "File creation error",
    "lack_channel": "Max channels used cannot add additional cameras",
    "no_heartbeat": "Connection timed out. Log in again!",
    "no_support": "no support",
    "default_failed": "Failed to restore default values",
    "device_busy": "The device is processing the maximum number of APIs",
    "user_expired_login": "User expired login",
    "user_locked_login": "User lock login",
    "netip_limited": "After the login IP is added to the blacklist",
    "forced_offline": "Force logout",
    "pwd_weak": "The modified IPC password has low complexity",
    "modify_failed_pwd_err": "Modifying IP user name or password error of IPC",
    "modify_failed_syntax_err": "Modifying IP syntax configuration error of IPC",
    "illegal_request": "Illegal request",
    "username_empty": "The user name is empty",
    "username_repeat": "repeat of user name",
    "username_invalid": "Only letters, numbers and underscores are allowed for the user name",
    "pwd_risk": "The password is weak",
    "service_unavailable_error": "Service not available",
    "ftp_close_failed": "Failed to shut down the FTP service",
    "Channel_limit": "More than max system channel num",
    "ipc_upgrading": "these ipc channels are being upgraded, please select again",
    "disk_changed": "Disk is changed!",
    "group_name_error": "The group name already exists, please modify",
    "user_error": "Please input a email user!",
    "bind_fail": "The device is already bind!",
    "unbind_fail": "The device isn't bind to any account!",
    "error_try_again": "An error has occurred. Please try again later.",
    "Network_or_DNS_error": "Network is unreachable or DNS is incorrect !",
    "latest_ver_not_find": "Unable To Find Latest Version",
    "no_data_in_time": "No data found, please adjust the time and try again!",
    "network_connection_overtime": "Network connection overtime.",
    "ddns_register_failed": "Your account is failed to register, please try again later.",
    "invalid_file": "Invalid upgrade file",
    "download_failed": "Download file failed",
    "file_already_exists": "File already exists",
    "file_size_exceeds_limit": "File size exceeds limit",
    "ipc_pwd_rule_tip1": "1. 8~9 characters: combination should consist of at least 3 from uppercase letters, lowercase letters, numbers or special characters.",
    "ipc_pwd_rule_tip2": "2. 10~15 characters: combination should consist of at least 2 from uppercase letters, lowercase letters, numbers or special characters.",
    "ipc_pwd_rule_tip3": "3. Repeated and continuous characters exceed 4-digit are prohibited. i.e., 6666/bbbb or 1234/abcd.",
    "ipc_pwd_rule_tip4": "4. Continuous keys of keyboard pattern exceed 4-digit are prohibited. i.e., qwer or ghjk",
    "cannot_upgrade": "There has no newer firmware available to upgrade.",
    "have_login": "Online client exceeds limit",
    "err_address_conflicting": "The address is used",
    "not_exist_necessary_params": "Not exist necessary params!",
    "id_or_password_error": "ID or password error!",
    "not_exist_data": "Not exist data!",
    "data_update_fail": "Data update fail!",
    "data_insert_fail": "Data insert fail!",
    "data_select_fail": "Data select fail!",
    "host_name_exit_unable_to_use": "Host name exit,unable to use!",
    "id_or_password_is_empty": "ID or password is empty!",
    "host_not_exit_able_to_use": "Host not exit,able to use!",
    "err_net_config_invalid": "The entered settings are incorrect! Check that the IP address, subnet mask, and default gateway are in the same segment of the subnet.",
    "file_formats_unsupported": "The file type is wrong!",
    "no_line_drawing": "Save failed! Please note the Rule Number(Detection Area) is not marked.",
    "need_close_tuya": "Need to close the Tuya!",
    "fd_pd_chn_limit": "__FD__ and __PD__ support the maximum number of channels",
    "target_detection_chn_limit": "The number of open channels for Target detection  has reached the maximum. Please refresh the page or close the relevant buttons",
    "email_must_verify": "The email address has changed, please re-verify the email address.",
    "email_verifycode_error": "Verification code error!",
    "preset_point_cruising": "Please stop the Cruise operation before using the PTZ setup!",
    "preset_point_empty": "Please add preset points",
    "part_group_failed": "The following group parameters failed to save",
    "http_listening_operation": "Please open Server Config ->Http Listening -> Enable",
    "err_filename_repeat": "The file name is duplicated, please change the file name",
    "disk_unavailable_for_upgrade": "No HDD is installed! It is allowed to upgrade the firmware only when there is at least one fully-functioning HDD installed.",
    "createRaid_name_empty": "Please input a name for the RAID.",
    "createRaid_name_repeated": "The Name is repeated",
    "createRaid_raid0_disk_num_less": "needs 2 diskes at least.",
    "createRaid_raid1_disk_num_less": "only supports 2 diskes",
    "createRaid_raid4_disk_num_less": "only supports 3/4/5 diskes",
    "createRaid_raid5_disk_num_less": "only supports 3/4/5 diskes",
    "createRaid_raid6_disk_num_less": "only supports 4/5/6 diskes",
    "createRaid_raid10_disk_num_less": "only supports 4/8 diskes",
    "deleteRaid_disk_num_empty": "Please select a RADID for delete.",
    "rebuild_disk_num_empty": "Please select a disk for rebuild",
    "server_mutually": "Server Mutual Exclusion [__SERVERS__] : Only one can be opened.",
    "time_error": "End time must be after the start time",
    "netdisk_connect_failed": "Connection hard disk failed",
    "join_failed": "Join failed!",
    "join_failed_no_discover": "SSID no discover",
    "join_failed_wifi_busy": "Wifi connect is busy, just return!",
    "join_failed_data_error": "Data error!",
    "server_connect_failed": "Connection failed",
    "downloading": "Repeated requests cause download failure",
    "function_busy": "Function busy",
}
